name: Pipeline N1 - Execução de Testes

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: windows-latest
    
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3  # Atualize para v3
        
      - name: Configurar Node.js
        uses: actions/setup-node@v3  # Atualize para v3
        with:
          node-version: '16'  # ou '20' para a versão mais recente
      
      - name: Instalar dependências
        run: npm install
      
      - name: Executar testes
        run: npm test
